### ISSUE TITLE
Unable to get feature flag status

### ISSUE THREAD

**Issue by tandrup** [launchdarkly/api-client-java#5]
I've tried to use this example to get status of all my feature flags:
https://github.com/launchdarkly/api-client-java/blob/master/docs/FlagsApi.md#getFeatureFlagStatus

But I get this parsing exception:
```Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "2018-02-15T13:28:50.02Z"
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:323)
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:313)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at io.swagger.client.JSON.deserialize(JSON.java:103)
	at io.swagger.client.ApiClient.deserialize(ApiClient.java:860)
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:1063)
	at io.swagger.client.ApiClient.execute(ApiClient.java:990)
	at io.swagger.client.api.FlagsApi.getFeatureFlagStatusesWithHttpInfo(FlagsApi.java:579)
	at io.swagger.client.api.FlagsApi.getFeatureFlagStatuses(FlagsApi.java:563)
	at com.schneiderelectric.ivan.launchdarkly.bot.LaunchdarklyBot.main(LaunchdarklyBot.java:27)
Caused by: java.lang.NumberFormatException: For input string: "2018-02-15T13:28:50.02Z"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:964)
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:321)
	... 13 more```

Seems like it's expecting a number but it's a date.

**Comment by brooswit** [comment]
Thanks for spotting this. I'll get it fixed right away.

**Comment by jazanne** [comment]
We have released our new OpenAPI v3 client. If you continue to have problems, don't hesitate to reopen the issue.
